LABELS = {
    "empty": " ",
    "black knight": "n",
    "black bishop": "b",
    "black king": "k",
    "black pawn": "p",
    "black queen": "q",
    "black rook": "r",
    "white knight": "N",
    "white bishop": "B",
    "white king": "K",
    "white pawn": "P",
    "white queen": "Q",
    "white rook": "R",
}
